-- =============================================================
-- SEED DATA - EDUFLOW SYSTEM
-- =============================================================
-- Este arquivo está vazio propositalmente para que o banco 
-- inicie apenas com dados reais criados pelo usuário.
